# config/database.yml

default: &default
  adapter: sqlserver
  host: <%= ENV.fetch("GSABSS_HOST") %>
  port: <%= ENV.fetch("GSABSS_PORT").to_i %>
  username: <%= ENV.fetch("GSABSS_USERNAME") %>
  password: <%= ENV.fetch("GSABSS_PASSWORD") %>
  database: <%= ENV.fetch("GSABSS_DATABASE", "GSABSS") %>
  azure: false
  timeout: <%= ENV.fetch("GSABSS_TIMEOUT").to_i %>
  encoding: utf8

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

gsabss:
  <<: *default
