# config/database.yml

default: &default
  adapter: sqlserver
  host: <%= ENV.fetch("GSABSS_HOST", "gsasql16") %>
  port: <%= ENV.fetch("GSABSS_PORT", 1433).to_i %>
  username: <%= ENV.fetch("GSABSS_USERNAME") %>
  password: <%= ENV.fetch("GSABSS_PASSWORD") %>
  database: <%= ENV.fetch("GSABSS_DATABASE", "GSABSS") %>
  azure: false
  timeout: 30000
  encoding: utf8

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

# Used by GsabssBase:
gsabss:
  <<: *default
